name: ddpg1
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pillow=6.1
  - mpi4py
  - pip:
    - termcolor
    - git+git://github.com/deepmind/dm_control.git
    - git+git://github.com/1nadequacy/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - torchvision
    - scikit-image
    - gym==0.12.5
    - git+git://github.com/openai/mujoco-py.git
    - glfw==1.12.0
    - numpy==1.20.1
